loglevel: debug
security:
  salt: replace-to-your-random-string
address:
  api: :8091
db:
  mongoDb:
    user: root
    password: test
    url: 127.0.0.1:27017
    dbname: media_archive
kafka:
  brokers:
  - 127.0.0.1:9092
admin:
  login: admin@admin.net
  password: admin
Jwt:
  SecretAccess: sdagdfdadgaASfsskjn
  AtExpires: 20h
  RtExpires: 168h