version: '2.2'
services:
  media_archive_backend:
    container_name: media_archive_backend
    image: media_archive_backend
    build:
      dockerfile: ../../docker/backend/Dockerfile
      context: ../backend/api
    ports:
      - "8091:8091"
    restart: on-failure
    environment:
      - DB_MONGODB_URL=mongodb-server-ma:27017
      - DB_MONGODB_USER=root
      - DB_MONGODB_PASSWORD=test
      - DB_MONGODB_DBNAME=media_archive
      - JWT_SECRETACCESS=sdagdfdadgaASfsskjn
      - JWT_ATEXPIRES=24h
      - JWT_RTEXPIRES=168h
      - ADDRESS_API=:8091
    depends_on:
      - mongodb
    networks:
      - media_archive
  mongodb:
    ports:
      - "27017:27017"
    container_name: mongodb-server-ma
    image: bitnami/mongodb:latest
    volumes:
      - mongodata:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=test
    networks:
      - media_archive
    restart: on-failure
  mongo-express:
    image: mongo-express
    container_name: mongo-express-ma
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb-server-ma
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=test
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    depends_on:
      - mongodb
    networks:
      - media_archive
    restart: on-failure
volumes:
  mongodata:
networks:
  media_archive:
    name: media_archive_network
    driver: bridge
